Traducción Español
lambdaclass/cairo-by-example pull request #71
Opened 2023-06-29 06:59 UTC by Nadai2010

Hola chicos, antes que nada Felicitaros una vez más por todo el trabajo realizado, os dejo por aquí las traducciones a Español para que revisen, gracias

2023-06-29 17:09 UTC, Nadai2010 commented
Perfecto la cambio luego, ahí algunas expresiones que deje literales, aunque creo que pueden ser mejoradas en ambos idiomas, por ahora me limité a dejar lo más parecido, cualquier modificación aquí estamos, gracias

2023-06-29 18:05 UTC, rcatalan98 commented on content/es/examples/functions.md
> +La norma de Cairo es nombrar las funciones utilizando la forma 'snake_case'. En el ejemplo anterior, el nombre de la función es `inc_n`.
Reemplazaría "norma" por "convención"

2023-06-29 18:06 UTC, rcatalan98 commented on content/es/examples/generics.md
> +En Cairo, puedes usar genéricos cuando defines `functions`, `structs`, `enums`, `traits`, `implementations`, y `methods`.
Ídem comentarios anteriores, conviene utilizar la palabra en inglés que suele ser lo más utilizado en estos contextos.

2023-06-29 18:11 UTC, rcatalan98 commented on content/es/examples/integers.md
> +Los tipos `integer` vienen con protección extra contra posibles vulnerabilidades en el código, como comprobaciones de desbordamiento.
```suggestion
Los tipos `integer` vienen con protección extra contra posibles vulnerabilidades en el código, como chequeos contra overflow
```

2023-06-29 18:12 UTC, rcatalan98 commented on content/es/examples/integers.md
> +Nótese que todos ellos son **sin signo**, igual que `felt252`.
```suggestion
Nótese que todos ellos son **unsigned**, igual que `felt252`.
```

2023-07-03 14:12 UTC, rcatalan98 requested changes
Gracias por tu colaboración! Dejamos un par de cambios que deben implementarse para poder mergearse.

2023-07-03 14:12 UTC, rcatalan98 commented on content/es/examples/structs.md
> +Una struc es una colección de campos con nombre. Es una de las formas de definir tipos de usuario personalizados.
```suggestion
Una struct es una colección de campos con nombre. Es una de las formas de crear tipos personalizados definidos por el usuario
```

2023-07-03 14:28 UTC, Nadai2010 commented on content/es/examples/structs.md
> +Una struc es una colección de campos con nombre. Es una de las formas de definir tipos de usuario personalizados.
Cambios realizados, gracias por la colaboración.

2023-07-03 14:36 UTC, rcatalan98 approved these changes
LGTM! Gracias por aportar a la comunidad!

2023-07-03 14:38 UTC, Nadai2010 commented
A ustedes, intentaremos entre todos hacer grandes avances.

2023-07-03 14:39 UTC, merged